services:
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      # - --providers.consulcatalog=true
      # - --providers.consulcatalog.endpoint.address=consul:${CONSUL_HTTP_PORT}
      # - --providers.consulcatalog.endpoint.token=${CONSUL_SERVICE_REGISTRATION_TOKEN}
      # - --providers.consulcatalog.exposedbydefault=false
      # - --accesslog=true
      # ACME 配置
      - --certificatesresolvers.cloudflare.acme.dnschallenge=true
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cloudflare.acme.email=${TRAEFIK_EMAIL}
      - --certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.cloudflare.acme.dnschallenge.delaybeforecheck=0
    ports:
      - "${TRAEFIK_HTTP_PORT}:80" # HTTP
      - "${TRAEFIK_HTTPS_PORT}:443" # HTTPS
      - "${TRAEFIK_DASHBOARD_PORT}:8080" # Traefik Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_data:/data
      - ./traefik/letsencrypt:/letsencrypt
    environment:
      - CF_DNS_API_TOKEN=${TRAEFIK_CF_DNS_API_TOKEN}
    networks:
      - common_network
    restart: unless-stopped
    # depends_on:
    #   - consul

  xray:
    image: teddysun/xray:latest
    container_name: xray
    restart: unless-stopped
    ports:
      - "${XRAY_VLESS_PORT:-10086}:10086"  # VLESS端口
      - "${XRAY_VMESS_PORT:-10087}:10087"  # VMess端口
    volumes:
      - ./xray/config.json:/etc/xray/config.json:ro
      - ./xray/logs:/var/log/xray
    environment:
      - TZ=${TZ:-UTC}
    networks:
      - common_network
    labels:
      # 启用traefik
      - "traefik.enable=true"
      
      # VLESS路由配置
      - "traefik.http.routers.xray-vless.rule=Host(`${XRAY_DOMAIN}`) && PathPrefix(`/vless`)"
      - "traefik.http.routers.xray-vless.entrypoints=websecure"
      - "traefik.http.routers.xray-vless.tls.certresolver=cloudflare"
      - "traefik.http.routers.xray-vless.service=xray-vless"
      - "traefik.http.services.xray-vless.loadbalancer.server.port=10086"
      
      # VMess路由配置
      - "traefik.http.routers.xray-vmess.rule=Host(`${XRAY_DOMAIN}`) && PathPrefix(`/vmess`)"
      - "traefik.http.routers.xray-vmess.entrypoints=websecure"
      - "traefik.http.routers.xray-vmess.tls.certresolver=cloudflare"
      - "traefik.http.routers.xray-vmess.service=xray-vmess"
      - "traefik.http.services.xray-vmess.loadbalancer.server.port=10087"
      
      # # WebSocket升级头和Cloudflare真实IP中间件
      # - "traefik.http.routers.xray-vless.middlewares=xray-headers,cloudflare-realip"
      # - "traefik.http.routers.xray-vmess.middlewares=xray-headers,cloudflare-realip"
      # - "traefik.http.middlewares.xray-headers.headers.customrequestheaders.Upgrade=websocket"
      # - "traefik.http.middlewares.xray-headers.headers.customrequestheaders.Connection=upgrade"
      
      # # Cloudflare真实IP中间件配置
      # - "traefik.http.middlewares.cloudflare-realip.ipwhitelist.sourcerange=173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22"
      # - "traefik.http.middlewares.cloudflare-realip.headers.customrequestheaders.X-Forwarded-Proto=https"
      # - "traefik.http.middlewares.cloudflare-realip.headers.customrequestheaders.X-Real-IP="
      # - "traefik.http.middlewares.cloudflare-realip.headers.customrequestheaders.X-Forwarded-For="

  # X-UI 管理面板
  x-ui:
    image: alireza7/x-ui:latest
    container_name: x-ui
    restart: unless-stopped
    # ports:
    #   - "${XUI_PORT:-54321}:54321"  # X-UI管理端口
    volumes:
      - xui_data:/etc/x-ui
    environment:
      - TZ=${TZ:-UTC}
    networks:
      - common_network
    labels:
      # 启用traefik
      - "traefik.enable=true"
      
      # X-UI管理面板路由配置
      - "traefik.http.routers.x-ui.rule=Host(`${XRAY_DOMAIN}`) && PathPrefix(`${XUI_PATH:-/xui}`)"
      - "traefik.http.routers.x-ui.entrypoints=websecure"
      - "traefik.http.routers.x-ui.tls.certresolver=cloudflare"
      - "traefik.http.routers.x-ui.service=x-ui"
      - "traefik.http.services.x-ui.loadbalancer.server.port=54321"
      
      # X-UI路径重写中间件
      - "traefik.http.routers.x-ui.middlewares=x-ui-stripprefix"
      - "traefik.http.middlewares.x-ui-stripprefix.stripprefix.prefixes=/xui"

networks:
  common_network:
    driver: bridge

volumes:
  traefik_data:
  xui_data:
