nginx:
  container_name: fd_nginx
  build: ./nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - D:/myproject/:/usr/share/nginx/html
    - ./nginx/conf/conf.d:/etc/nginx/conf.d
  links:
    - php-fpm

php-fpm:
    container_name: fd_php-fpm
    build: ./php
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - D:/myproject/:/usr/share/nginx/html
    restart: always
    links:
      - memcached
memcached:
    container_name: fd_memcached
    build: ./memcached
    restart: always
    ports:
      - "11211:11211"
    environment:
      - MEMCACHED_CACHE_SIZE=128