# tomcat:
#     container_name: tomcat
#     build: ./tomcat
#     ports:
#       - "8080:8080"
# java:
#     container_name: java
#     build: ./java
#     tty: true
#     # restart: always
mysql:
    container_name: mysql
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      # MYSQL_USER: 'root'
      # MYSQL_PASS: '123456'
    ports:
      - "3306:3306"
    volumes:
      - /Users/lebbay/soft/mysql/data:/var/lib/mysql
redis:
    container_name: redis
    build: ./redis
    restart: always
    ports:
      - "6379:6379"
    command:
      redis-server
rabbitmq:
    image: rabbitmq:management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"