version: '3.8'

services:
  next-chat:
    image: yidadaa/chatgpt-next-web
    container_name: next-chat
    restart: always
    ports:
      - "3000:3000"
    environment:
      OPENAI_API_KEY: ${NEXT_CHAT_OPENAI_API_KEY}
      BASE_URL: ${BASE_URL}
      CODE: ${NEXT_CHAT_ACCESS_CODE}
  lobe-chat:
    image: lobehub/lobe-chat
    container_name: lobe-chat
    restart: always
    ports:
      - '3210:3210'
    environment:
      OPENAI_API_KEY: ${LOBE_CHAT_OPENAI_API_KEY}
      OPENAI_PROXY_URL: ${BASE_URL}
      ANTHROPIC_API_KEY: ${LOBE_CHAT_OPENAI_API_KEY}
      ANTHROPIC_PROXY_URL: ${ANTHROPIC_PROXY_URL}
      ACCESS_CODE: ${LOBE_CHAT_ACCESS_CODE}
      #NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${LOBE_CHAT_NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      #CLERK_SECRET_KEY: ${LOBE_CHAT_CLERK_SECRET_KEY}
