version: '3.8'

services:
  next-chat:
    image: yidadaa/chatgpt-next-web
    container_name: next-chat
    restart: always
    ports:
      - "3000:3000"
    environment:
      OPENAI_API_KEY: ${NEXT_CHAT_OPENAI_API_KEY}
      BASE_URL: ${BASE_URL}
      ANTHROPIC_API_KEY: ${NEXT_CHAT_OPENAI_API_KEY}
      ANTHROPIC_URL: ${ANTHROPIC_PROXY_URL}
      CODE: ${NEXT_CHAT_ACCESS_CODE}
  lobe-chat:
    image: lobehub/lobe-chat
    container_name: lobe-chat
    restart: always
    ports:
      - '3210:3210'
    environment:
      OPENAI_API_KEY: ${LOBE_CHAT_OPENAI_API_KEY}
      OPENAI_PROXY_URL: ${BASE_URL}
      ANTHROPIC_API_KEY: ${LOBE_CHAT_OPENAI_API_KEY}
      ANTHROPIC_PROXY_URL: ${ANTHROPIC_PROXY_URL}
      OPENAI_MODEL_LIST: +claude-3-5-sonnet=Claude 3.5 Sonnet(自定义)<200000:vision:fc>,+claude-3-haiku=Claude 3 Haiku(自定义)<200000:vision:fc>,+claude-3-sonnet=Claude 3 Sonnet(自定义)<200000:vision:fc>,+claude-3-opus=Claude 3 Opus(自定义)<200000:vision:fc>
      ACCESS_CODE: ${LOBE_CHAT_ACCESS_CODE}
      #NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${LOBE_CHAT_NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      #CLERK_SECRET_KEY: ${LOBE_CHAT_CLERK_SECRET_KEY}
  one-api:
    image: justsong/one-api
    container_name: one-api
    restart: always
    ports:
      - "3300:3000"
    environment:
      TZ: Asia/Shanghai
      # 个人使用，暂时不需要数据库
      # SQL_DSN: ${ONEAPI_DB_USER}:${ONEAPI_DB_PWD}@tcp(${ONEAPI_DB_HOST}:${ONEAPI_DB_PORT})/oneapi
    volumes:
      - ${ONEAPI_DATA_PATH}:/data