name: lobe-chat-database
services:
  postgresql:
    image: pgvector/pgvector:pg16
    container_name: lobe-postgres
    ports:
      - '5432:5432'
    volumes:
      - './data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_USER=${DATABASE_USER}'
      - 'POSTGRES_DB=lobe'
      - 'POSTGRES_PASSWORD=${DATABASE_PASSWORD}'
      - 'TZ=Asia/Shanghai'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DATABASE_USER}']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  minio:
    image: minio/minio
    container_name: lobe-minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - './s3_data:/etc/minio/data'
    environment:
      - 'MINIO_ROOT_USER=${MINIO_ROOT_USER}'
      - 'MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}'
      - 'MINIO_DOMAIN=${S3_PUBLIC_DOMAIN}'
      - 'MINIO_API_CORS_ALLOW_ORIGIN=${APP_URL}' # Your LobeChat's domain name.
    env_file:
      - .env
    restart: always
    command: >
      server /etc/minio/data --address ":9000" --console-address ":9001"


  # logto:
  #   image: svhd/logto
  #   container_name: lobe-logto
  #   ports:
  #     - '3001:3001'
  #     - '3002:3002'
  #   depends_on:
  #     postgresql:
  #       condition: service_healthy
  #   environment:
  #     - 'TRUST_PROXY_HEADER=1'
  #     - 'DB_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@postgresql:5432/logto'
  #     - 'ENDPOINT=${AUTH_LOGTO_ENDPOINT}'
  #     - 'ADMIN_ENDPOINT=${AUTH_LOGTO_ADMIN_ENDPOINT}'
  #     # - 'LIMITER_MAX_ATTEMPTS=5'
  #     # - 'LIMITER_DURATION_SECONDS=300'
  #   entrypoint: ['sh', '-c', 'npm run cli db seed -- --swe && npm start']

  lobe:
    build: ./lobe-chat
    container_name: lobe-chat
    ports:
      - '3210:3210'
    depends_on:
      - postgresql
      - minio
      # - logto
    env_file:
      - .env
    restart: always

volumes:
  data:
    driver: local
  s3_data:
    driver: local